### ISSUE TITLE
Only works in Incognito

### ISSUE THREAD

**Issue by pro-arch-user** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#246] opened 2024-07-19 00:01 UTC
### What happened?

The script only work when I open the link in incognito and I am signed OUT of my google account. Otherwise it simply freezes on the thumbnail and doesn't load.
I am using: Violentmonkey, Brave, Windows

### Platform

Userscript

### Version

latest and greatest

### What browser are you on?

Brave

### Browser version

latest and greatest

### Link to the video

https://www.youtube.com/watch?v=zGN959Wt5SY

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment] 2024-07-19 00:05
Duplicate of https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/236.

**Closed by drunkwinter** 2024-07-19 00:05 UTC
Labels: bug

**Comment by pro-arch-user** [comment] 2024-07-20 18:11
Well it would be nice if you could at least tell us somewhere that we have to use it in incognito. Not just close the github issues.

**Comment by drunkwinter** [comment] 2024-07-20 21:06
Yes, that's why I linked the original issue before closing it as duplicate. Since you didn't read I'll summarize it for you.

It is a Brave bug. It has to be fixed on their side. There are only workarounds, such as incognito and turning off a feature flag.

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/236#issuecomment-2052260364
> as mentioned here you need to disable brave-ai-chat flag [brave/brave-browser#37341 (comment)](https://github.com/brave/brave-browser/issues/37341#issuecomment-2048166141)
> 
> since its a brave bug i think this issue can be closed
