### ISSUE TITLE
Doesnt work anymore

### ISSUE THREAD

**Issue by LaN1SteR** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#249] opened 2024-08-08 19:23 UTC
### What happened?

It recently stopped working on both extensions, Tampermonkey and Violentmonkey, firstly it happened on Tampermonkey, but right now it doesnt work on Violentmonkey too

### Platform

Extension

### Version

2.5.9

### What browser are you on?

Chrome

### Browser version

126.0.6478.127

### Link to the video

https://www.youtube.com/watch?v=8nSt0PYS1d0

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by WinterPhoenix** [comment] 2024-08-09 04:42
Duplicate of https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/247. Update your script

**Comment by drunkwinter** [comment] 2024-08-09 12:25
Yes, like mentioned above this has been fixed recently. But It's completely on us, something went wrong with the releasing process and the upload to Greasyfork failed. The new version will be available on there as soon as possible.

**Comment by drunkwinter** [comment] 2024-08-11 13:23
The latest version has now been published to Greasyfork.

**Closed by drunkwinter** 2024-08-11 13:23 UTC
Labels: bug
