### ISSUE TITLE
Does not bypass administrator restrictions

### ISSUE THREAD

**Issue by UberSuperBoss** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#55] opened 2021-08-23 08:28 UTC
![image](https://user-images.githubusercontent.com/44003432/130415631-ffbc1a59-04e1-407a-b83a-9bae74d01ed2.png)
Please bypass this, school Chromebooks block basically everything and it's extremely annoying!

Thanks

**Comment by zerodytrash** [comment] 2021-08-23 16:52
hi,

this has nothing to do with age restrictions? You can try to enter the generated playablilityStatus under `unlockablePlayerStates`.

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/blob/09da4a68c3867ce8df53cb8747afeec930806f56/Simple-YouTube-Age-Restriction-Bypass.user.js#L31

**Comment by coletdjnz** [comment] 2021-08-25 08:51
I'm curious if it is possible to bypass this with a param under user in the payload.
For example, enabling restricted mode manually toggles "lockedSafetyMode". I wonder if it is the same for the network restricted more, or if there is another param.

normal restricted mode disabled:
```json
{
  "context": {
    "client": {
      "hl": "en",
      "clientName": "WEB",
      "clientVersion": "2.20210824.00.00"
      }
    },
    "user": {
      "lockedSafetyMode": false 
    }
}
```

Unfortunately I don't have access to any restricted networks like this to test it on. If OP can check the /player request in their browser for what comes under "user" it might help.

**Comment by UberSuperBoss** [comment] 2021-08-25 14:44
I know it has nothing to do with age restriction but I was wondering if it was possible. You could make it "Youtube Restriction Bypass" instead of just age restriction. I would love to help but my knowledge of things like html is around... zero. If you could tell me how I would be more than happy to help.

**Comment by drunkwinter** [comment] 2021-12-16 01:16
Closing since the issue is unrelated to what the repo is trying to solve.

**Closed by drunkwinter** 2021-12-16 01:16 UTC
