### ISSUE TITLE
Issue with the Age-Restriction-Bypass script

### ISSUE THREAD

**Issue by Knov1** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#271] opened 2024-11-20 00:20 UTC
### What happened?

Hello!

Your script no longer works when I come across a video with an age restriction. The browser crashes (on my default browser: Brave), and on Chrome, the video and the site load, but the bypass no longer works!

Here are two screenshots taken on a video that requires age verification: one on Brave (my daily browser) with the script and another on Chrome (for testing).

That’s it! Hoping for a fix soon ! :)

And thanks!
![Screenshot_1](https://github.com/user-attachments/assets/fd28a4ee-efb5-4d63-bad2-52db7945f79d)
![Screenshot_4](https://github.com/user-attachments/assets/880b905d-68f7-48a4-bfd6-1777dfe45556)

### Platform

Other (mention above)

### Version

2.5.11

### What browser are you on?

Brave

### Browser version

1.73.89(for brave), 131.0.6778.70(for Google Chrome)

### Link to the video

https://www.youtube.com/watch?v=fb1MR85XFOc

### About you

- [X] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment] 2024-11-20 14:56
Duplicate of #236.

Workaround: https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/236#issuecomment-2052260364

**Closed by drunkwinter** 2024-11-20 14:56 UTC
Labels: bug
