### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by MusicaFM** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#266] opened 2024-10-31 15:27 UTC
### What happened?

El proxy está off y por eso actualmente no funciona, probado en kiwibrowser y firefox android

### Platform

Other (mention above)

### Version

Actual

### What browser are you on?

Chrome

### Browser version

Actual

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment] 2024-10-31 21:06
Duplicate of #262, #263.

**Closed by drunkwinter** 2024-10-31 21:06 UTC
Labels: bug
