### ISSUE TITLE
[Pale Moon] not working anymore

### ISSUE THREAD

**Issue by ask2018** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#183] opened 2023-03-19 22:22 UTC
### What happened?

There seems to be some change on Youtube side and it is not working anymore. I'm getting "Sign in to confirm your age" since today.

### Platform

Userscript

### Version

2.5.4

### What browser are you on?

Other (mention below with version)

### Browser version

Pale Moon 32.0.1

### Link to the video

https://www.youtube.com/watch?v=EY_9OZxqStY

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by navas-n** [comment] 2023-03-21 13:28
in my case the entire extension is missing from the mozilla addons store

**Comment by drunkwinter** [comment] 2023-03-21 20:56
I could not reproduce the issue you are having. Tested with the latest versions of Chrome and Firefox.

Could you provide me with the logs in the console you are getting while trying to unlock the video?
1. Press the F12 key or go to the "Tools" menu and select "Web Developer" > "Web Console."
2. The console will appear at the bottom of the browser window. If it's not visible, click on the "Console" tab.

Please also check if the userscript is indeed enabled and there are no other conflicting userscripts/extensions.

**Comment by drunkwinter** [comment] 2023-03-21 21:01
> in my case the entire extension is missing from the mozilla addons store

Not related. Read below (from [readme](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass#browser-extension)):

> 
> Unfortunately, our Firefox extension was removed from Mozilla add-ons and disabled on Edge add-ons due to a violation of their terms of service.
> 
> As a result, we can no longer provide updates for it. However, the extension can still be installed manually.
> 
> We're looking for ways to make this process easier.

**Comment by drunkwinter** [comment] 2023-03-21 21:28
I don't know why, but it seems like the issue is on your end. Your system seems to be having an issue connecting to our proxy server at https://youtube-proxy.zerody.one.

**Comment by ask2018** [comment] 2023-03-21 21:32
Problem inside yt-dlp confirmed also friend of mine. I can ask him to test this script as well. If I try to open https://youtube-proxy.zerody.one/ in my browser, I'm getting redirect to this github page https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass

**Comment by drunkwinter** [comment] 2023-03-21 21:41
> If I try to open https://youtube-proxy.zerody.one/ in my browser, I'm getting redirect to this github page https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass

That's fine. Did you try the script out on a different browser or userscript manager, can you confirm it works there?

**Comment by ask2018** [comment] 2023-03-21 21:49
> > If I try to open https://youtube-proxy.zerody.one/ in my browser, I'm getting redirect to this github page https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass
> 
> That's fine. Did you try the script out on a different browser or userscript manager, can you confirm it works there?

I just tried Brave browser and Tampermonkey and there it works.

**Comment by drunkwinter** [comment] 2023-03-21 21:55
That means the problem is either Greasemonkey or Pale Moon. Pale Moon supports all Firefox add-ons right? You could try Tampermonkey or Violentmonkey in that case. I'm interested in seeing if Greasemonkey is the problem here.

**Comment by ask2018** [comment] 2023-03-21 21:57
I'm trying now another instance of Palemoon portable with fully clean profile and without any other addons or scripts and there it is working as well. That's really odd, because as I have said I have the same issue as well in the yt-dlp and that's not browser related at all.

**Comment by drunkwinter** [comment] 2023-03-21 22:08
Alright, glad you got it working. Closing the issue as complete.

**Closed by drunkwinter** 2023-03-21 22:08 UTC
Labels: bug

**Comment by ask2018** [comment] 2023-03-21 22:23
So I have found the reason why it was not working in my main browser. I needed to allow javascript from zerody.one domain. But this was not needed before. So you maybe changed something related to the javascript recently on proxy and that might be as well the reason why yt-dlp doesn't work in case they are using your proxyserver?

**Comment by drunkwinter** [comment] 2023-03-21 22:32
That's weird. The domain does not contain or run any javascript. We simply get the unlocked video data in JSON file format. It must've been some sort of a "privacy" update to your browser, because we haven't had a new release since **Nov 12, 2022**.

**Comment by ask2018** [comment] 2023-03-21 22:35
Odd, because I have auto updates disabled in my browser and didn't do any manual during those days as well. How about the yt-dlp? Any idea if they using your proxy server? Because there I'm getting the bypass issue exactly since I got the issues here in the browser.

**Comment by drunkwinter** [comment] 2023-03-21 23:02
No they are not. We are using a couple local bypass strategies and if those fail we have the proxy server as a fallback. yt-dlp only has local bypasses to my knowledge. I think both our bypasses failed because of a YouTube change. The proxy server probably never has worked on your end anyway.

**Comment by ask2018** [comment] 2023-03-21 23:08
Ah now it makes finally sense to me. Thank you for explanation. So basically there was really Youtube change, but because of local bypasses has been working before just fine for me, I was never forced to enable the proxy method on different domain in my privacy settings.

**Comment by drunkwinter** [comment] 2023-03-21 23:12
Probably ;)
