### ISSUE TITLE
can you make the bypass work on youtube shorts

### ISSUE THREAD

**Issue by Deadlydarty** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#196] opened 2023-07-24 10:59 UTC
### What's the problem this feature will solve?

an idea to discover more thing on youtube

### Describe the solution you'd like

to make the bypass work on youtube shorts

**Comment by drunkwinter** [comment] 2023-07-24 23:02
Duplicate of #195

**Closed by drunkwinter** 2023-07-24 23:02 UTC
Labels: enhancement
