### ISSUE TITLE
it doesnt work anymore AUTOR FIX THIS

### ISSUE THREAD

**Issue by MarkoczekTV** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#10] opened 2021-05-14 12:06 UTC
it doesnt work anymore AUTOR FIX THIS

**Comment by zerodytrash** [comment] 2021-05-16 22:09
The problem is addressed here: https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/9

Unfortunately, the problem does not affect all users, so it is not clear at the moment what exactly the problem is.

Feel free to share more information about the bug e.g. browser version, installed Extensions, affected Video(s). Furthermore, the developer console (F12) can provide information about the error.

**Comment by MarkoczekTV** [comment] 2021-05-19 13:37
![image](https://user-images.githubusercontent.com/80894547/118822012-102fe680-b8b8-11eb-867f-3d777009be6b.png)

**Comment by MarkoczekTV** [comment] 2021-05-19 13:37
idk what causes them

**Comment by MarkoczekTV** [comment] 2021-05-19 13:37
when i first writed this issue then yesterday it was working

**Comment by MarkoczekTV** [comment] 2021-05-19 13:38
so i need to use this script until fix comes up
https://greasyfork.org/pl/scripts/407977-yt-redirect-to-invidious-on-login-request

**Comment by MarkoczekTV** [comment] 2021-05-19 13:38
you can try fixing it with this code

**Comment by MarkoczekTV** [comment] 2021-05-19 13:41
i use cent browser
version newest

**Comment by MarkoczekTV** [comment] 2021-05-19 13:41
maybe there is new state

**Comment by MarkoczekTV** [comment] 2021-05-19 13:42
how do you find those state's?

**Comment by MarkoczekTV** [comment] 2021-05-19 13:43
WEB_PLAYER_CONTEXT_CONFIG_ID_KEVLAR_WATCH

**Comment by MarkoczekTV** [comment] 2021-05-19 13:43
?

**Comment by ner00** [comment] 2021-05-22 00:04
> 
> 
> so i need to use this script until fix comes up
> https://greasyfork.org/pl/scripts/407977-yt-redirect-to-invidious-on-login-request

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/9#issuecomment-846149419

**Comment by zerodytrash** [comment] 2021-06-04 01:38
Should be fixed in the latest version

**Closed by zerodytrash** 2021-06-04 01:38 UTC
