### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by HeyThereIsABugHere** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#245] opened 2024-07-11 12:14 UTC
### What happened?

When trying to view a restricted video the browser freeze.
I tried with both tampermonkey and violentmonkey.

### Platform

Extension

### Version

2.5.9

### What browser are you on?

Brave

### Browser version

1.67.123

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment] 2024-07-12 21:47
Duplicate of #236.

**Closed by drunkwinter** 2024-07-12 21:47 UTC
Labels: bug, duplicate
