### ISSUE TITLE
Content warning bypass not working

### ISSUE THREAD

**Issue by MrEnigmaSr** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#256] opened 2024-09-30 08:48 UTC
### What happened?

I go to the page, it tells me that the 'age restriction bypass' was successful.
it buffers forever and never loads -or- it plays the first part of the video but never downloads the rest.

### Platform

Userscript

### Version

2.4.6

### What browser are you on?

Firefox

### Browser version

Waterfox G6.0.19 (64-bit

### Link to the video

https://www.youtube.com/watch?v=8ahN0f0r9JQ

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/5b11bae9-57e6-4824-94fe-845e7b2689e9)

### About you

- [X] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment] 2024-09-30 17:07
Hi, I've been trying to fix/debug this issue for a week now and unfortunately the only solution I have right now is to play those videos at 360p. Which obviously is not good. I'll look into it again when I've got more free time.

**Comment by supersmith2500** [comment] 2024-10-01 18:56
So Google found it and broke it then?
Kiss Mortal Kombat videos bye then I guess?

**Comment by drunkwinter** [comment] 2024-10-31 21:18
@supersmith2500 Yes, unfortunately.

Closing this in favor of other already opened issues.

Duplicate of https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/262, https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/263.

**Closed by drunkwinter** 2024-10-31 21:18 UTC
Labels: bug
