### ISSUE TITLE
Error 282054944

### ISSUE THREAD

**Issue by Makloficz** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#200] opened 2023-07-30 19:33 UTC
# Description
[Please explain the problem/bug/behavior]
Hello im getting this error every time i want to play something. Is there a possible fix?
# Log
```

21:31:05 [INFO] playerResponse property set, contains sidebar: true
21:31:05 [INFO] playerResponse property set, contains sidebar: false
21:31:07 [INFO] Script injected (https://www.youtube.com/watch?v=IJAVTEtf9eU)
21:31:08 [INFO] playerResponse property set, contains sidebar: false
21:31:08 [INFO] Trying Player Unlock Method #2 (TV Embedded Player)
21:31:09 [INFO] playerResponse property set, contains sidebar: false
21:31:10 [INFO] Trying Next Unlock Method #2 (Account Proxy)
21:31:11 [ERROR] Failed to intercept Request(); url is null
unlockGoogleVideo@https://www.youtube.com/watch?v=IJAVTEtf9eU:1097:47

21:31:11 [ERROR] Failed to intercept Request(); url is null
unlockGoogleVideo@https://www.youtube.com/watch?v=IJAVTEtf9eU:1097:47

21:31:13 [INFO] playerResponse property set, contains sidebar: true
21:31:13 [INFO] playerResponse property set, contains sidebar: false
21:31:19 [INFO] Script injected (https://www.youtube.com/watch?v=IJAVTEtf9eU)
21:31:19 [INFO] playerResponse property set, contains sidebar: false
21:31:19 [INFO] Trying Player Unlock Method #2 (TV Embedded Player)
21:31:21 [INFO] playerResponse property set, contains sidebar: false
21:31:21 [INFO] Trying Next Unlock Method #2 (Account Proxy)
21:31:22 [ERROR] Failed to intercept Request(); url is null
unlockGoogleVideo@https://www.youtube.com/watch?v=IJAVTEtf9eU:1097:47

21:31:22 [ERROR] Failed to intercept Request(); url is null
unlockGoogleVideo@https://www.youtube.com/watch?v=IJAVTEtf9eU:1097:47

21:31:23 [INFO] playerResponse property set, contains sidebar: true
21:31:23 [INFO] playerResponse property set, contains sidebar: false

```

**Comment by drunkwinter** [comment] 2023-07-30 21:04
Duplicate of #197, #195, #191.

> Hi, this issue was fixed with [v2.5.7](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/releases/tag/v2.5.7).
> 
> Unfortunately the extension got removed from Edge Add-ons, so only a manual install is possible.

**Closed by drunkwinter** 2023-07-30 21:04 UTC
