### ISSUE TITLE
Description link colors don't respect current theme

### ISSUE THREAD

**Issue by Jamesgsburns** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#181] opened 2023-02-24 18:47 UTC
### What happened?

I was expecting one of you to notice, it must have been the update.

### Platform

Userscript

### Version

2.5.4

### What browser are you on?

Chrome

### Browser version

Present version

### Link to the video

https://www.youtube.com/watch?v=ykC7HZ1-FrQ

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/121324756/221265600-f6df21cb-1f59-43c4-9e75-e0f509553d98.png)

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment] 2023-02-24 23:00
Was not able to reproduce, but did notice that it looked different with the script on.

![image](https://user-images.githubusercontent.com/38593134/221316142-b8ad310b-3428-4ea7-b920-5ef8075c2fe2.png)

**Comment by drunkwinter** [comment] 2023-02-25 02:30
Alright looks like I might have found where the problem is. YouTube has something called 'attributed description' which includes text colors based on the current theme, but the proxy always assumes we are in dark theme. Hence why the description may look weird with the light theme on.

@zerodytrash We probably need to get this from the client, but there is no way for me to test if this actually fixes it.

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/blob/a80c32ac3663fac7f1d9876d429a688b7ce40596/account-proxy/lib/innertubeApi.js#L31

**Comment by drunkwinter** [comment] 2023-02-27 00:38
Ok, I just figured that I could test this with non age restricted videos and it did work.

The fix will be included in the next release. Thanks for reporting.

@zerodytrash

**Comment by drunkwinter** [comment] 2023-05-23 23:13
Fixed in [2.5.5](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/releases/tag/v2.5.5)

**Comment by Jamesgsburns** [comment] 2023-06-17 16:52
"Fixed in 2.5.5"
Oh really now? I even checked and it was in the current update and I reinstalled it and...!
https://github-production-user-asset-6210df.s3.amazonaws.com/121324756/246622045-7e9af270-e375-4efc-8c5b-af4d2f6f33b2.png

**Comment by drunkwinter** [comment] 2023-06-17 19:33
The proxy server probably still runs on old code and needs to be updated.

@zerodytrash Could we improve the process by auto deploying somehow?

**Comment by drunkwinter** [comment] 2023-06-21 00:27
I thought this was only going to be a server side fix, but we found a bug in the client...

@Jamesgsburns Could you try out this build?

- [Simple-YouTube-Age-Restriction-Bypass.user.zip](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/files/11810586/Simple-YouTube-Age-Restriction-Bypass.user.zip)

**Comment by Jamesgsburns** [comment] 2023-06-21 20:05
That didn't work for me...

**Comment by drunkwinter** [comment] 2023-06-21 23:10
> That didn't work for me...

How about this one:
- [Simple-YouTube-Age-Restriction-Bypass.user.zip](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/files/11826851/Simple-YouTube-Age-Restriction-Bypass.user.zip)

> Also last night, the sidebar and description were missing again and they just came back but not only did it NOT fix this issue

Yes, when updating the server a regression was found, which then resulted in bad responses. This is now solved.

> but that did NOT fix issue https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/169 either

This was not mean to fix issue #169, that's unrelated.

**Comment by Jamesgsburns** [comment] 2023-06-22 14:48
Unfortunately that did the exact same thing. It could be because it says it's an unknown publisher, I'm not the best with files.
Is there any possible way to just have it show just the youtube link itself or use some userscript or extension anywhere?

**Comment by drunkwinter** [comment] 2023-06-22 18:00
@Jamesgsburns 

If you have Tampermonkey:

1. Disable the current  `Simple-YouTube-Age-Restriction-Bypass`

2. Click on `Create a new script`

![image](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/assets/38593134/1571b4af-ab70-4b7c-998e-517a25268dd0)

3. Delete everything and then copy and paste the contents of this file:
[Simple-YouTube-Age-Restriction-Bypass.user.js.txt](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/files/11837737/Simple-YouTube-Age-Restriction-Bypass.user.js.txt)

4. Save by pressing CTRL+S or clicking on File -> Save

**Comment by Jamesgsburns** [comment] 2023-06-22 18:26
OMG that worked? Is there any way to update the userscript with that? Keep this issue open for the other people.
Something strange I should say is that the YouTube link update came out when they changed the layout in October, but that didn't happen to me until this issue happened. At the end of September, the description was gone but later on at the beginning of October it came back but it had this issue. But then in November, it was back to becoming actual links. I don't get why the updated description happened originally that late for me...

**Comment by drunkwinter** [comment] 2023-06-22 18:44
Alright I'll close this issue when the next version is released.

**Comment by drunkwinter** [comment] 2023-06-24 01:07
Fixed in [2.5.6](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/releases/tag/v2.5.6).

**Closed by drunkwinter** 2023-06-24 01:07 UTC
Labels: bug
