### ISSUE TITLE
Sidebar not loading more videos

### ISSUE THREAD

**Issue by Jamesgsburns** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#176] opened 2023-01-23 21:20 UTC
### What happened?

When scrolling down to find another video to watch, I noticed that there wasn't more videos loading in, I also checked with my phone and it's the same there.

### Platform

Userscript

### Version

2.5.4

### What browser are you on?

Chrome

### Browser version

4.18.1

### Link to the video

https://www.youtube.com/watch?v=dqRZDebPIGs

### Screenshots or Videos

https://user-images.githubusercontent.com/121324756/214151382-30b11500-f5be-48b5-961c-130e43b57c5e.PNG 

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment] 2023-01-23 21:44
Duplicate of issue #169.

Thanks for reporting anyway, we are looking into it.

**Closed by drunkwinter** 2023-01-23 21:44 UTC
Labels: bug, duplicate
