### ISSUE TITLE
Icon doesn't change if enabled

### ISSUE THREAD

**Issue by bachig26** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#146] opened 2022-06-26 11:20 UTC
The extension icon doesn't change in v2.5.1, as it stays as disabled icon even if the extension is enabled.

Chromium version: 102.0.5005.136

**Comment by drunkwinter** [comment] 2022-06-26 16:52
Cannot seem to reproduce

**Comment by zerodytrash** [comment] 2022-06-26 18:32
The icon only changes to active when then extension is enabled AND you visit youtube. Are you aware of this? @bachig26

**Comment by bachig26** [comment] 2022-06-26 19:47
> The icon only changes to active when then extension is enabled AND you visit youtube. Are you aware of this? @bachig26 

Yes, I enabled the extension and visited the YouTube. The bypass works but the icon stays/shows as deactivated/disabled.

**Comment by drunkwinter** [comment] 2022-06-27 15:08
Really weird, because if the script injection still succeeded, that must mean it failed in the `try..catch` block. If not then `chrome.runtime.sendMessage` or `chrome.runtime.onMessage.addListener`  somehow don't work as expected...

**Comment by zerodytrash** [comment] 2022-06-27 15:22
> Really weird, because if the script injection still succeeded, that must mean it failed in the try..catch block.

then an error message should appear in the debug log of the extension. 
Have installed the extension on several devices. No problems at all. Maybe it is a Chrome configuration problem.

> If not then chrome.runtime.sendMessage or chrome.runtime.onMessage.addListener somehow don't work as expected.

Then also the logging should not work so that the log is completely empty and also no "[INFO] Script injected" messages gets logged when visiting youtube. @bachig26 can you check this?

**Comment by bachig26** [comment] 2022-06-27 16:55
> Then also the logging should not work so that the log is completely empty and also no "[INFO] Script injected" messages gets logged when visiting youtube. @bachig26 can you check this?

Sure, I'll try check for error messages and logs and reply back soon. 👍

**Comment by zerodytrash** [comment] 2022-08-12 16:43
Apparently, only @bachig26 had the problem. I close it because it is not reproducible.
We can reopen the issue when we have more information about the problem.

**Closed** 2022-08-12 16:43 UTC
Labels: bug

**Comment by drunkwinter** [comment] 2022-08-12 18:52
Could've been [this](https://bugs.chromium.org/p/chromium/issues/detail?id=1316588&q=Event%20handlers%20registered%20via%20chrome.browserAction.onClicked.addListener%20should%20get%20dispatched%20to%20when%20the%20browser%20action%20button%2Ficon%20is%20clicked%20by%20the%20user&can=2) chromium bug. Apparently It's some kind of rare bug, possibly a race condition, where events are not being registered.
