### ISSUE TITLE
Not showing the description

### ISSUE THREAD

**Issue by serfeorumen** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#56] opened 2021-08-23 11:16 UTC
As mencioned in the title, I'm not able to see what the description says, it is just a blank space
If you could fix it, thanks.

**Comment by zerodytrash** [comment] 2021-08-23 14:11
yes, but duplicate of https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/52

**Closed by zerodytrash** 2021-08-23 14:11 UTC
