### ISSUE TITLE
It doesn't work anymore!

### ISSUE THREAD

**Issue by TheG-Mann** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#264] opened 2024-10-27 21:02 UTC
### What happened?

I used to use this userscript all the time on YouTube, but now it doesn't f#$king WORK anymore! Every single Age Restricted video I have tried, I am met with "Unable to unlock this video 🙁 - More information in the developer console (ProxyError)" WTF does that even mean? 

https://github.com/user-attachments/assets/c11a688b-d844-4031-839b-cbfcf3458ed2

### Platform

Userscript

### Version

2.5.10

### What browser are you on?

Brave

### Browser version

Version 1.71.118 Chromium: 130.0.6723.70 (Official Build) (64-bit)

### Link to the video

https://www.youtube.com/watch?v=Eyyy2_agdBQ

### Screenshots or Videos

![Screenshot (6)](https://github.com/user-attachments/assets/fd806c6e-a698-4235-9240-2e276756736e)

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment] 2024-10-31 21:06
Duplicate of #262, #263.

**Closed by drunkwinter** 2024-10-31 21:06 UTC
Labels: bug
