### ISSUE TITLE
Script doesnt work as of now, Error code: STATUS_BREAKPOINT

### ISSUE THREAD

**Issue by Tidoto** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#257] opened 2024-09-30 11:32 UTC
### What happened?

edit: doesnt work at all .-. playlist link: https://www.youtube.com/watch?v=rUc17RFUR3E&list=PLwK_l4xX9gRI4GPPLEhxozeJ8j-iQ4OVd&index=48 video link: https://www.youtube.com/watch?v=rUc17RFUR3E

### Platform

Userscript

### Version

2.5.11

### What browser are you on?

Brave

### Browser version

Version 1.70.119 Chromium: 129.0.6668.70 (Official Build) (64-bit)

### Link to the video

https://www.youtube.com/watch?v=rUc17RFUR3E&list=PLwK_l4xX9gRI4GPPLEhxozeJ8j-iQ4OVd&index=48

### About you

- [X] I am a developer and/or have knowledge in programming

**Comment by black-ish** [comment] 2024-09-30 18:32
Works for me.
Floorp (Firefox Fork) and Vivaldi (Chromium Fork).

**Comment by Tidoto** [comment] 2024-10-01 07:13
clearly you didnt notice that youre using a different browser

**Comment by ArazEstPrit** [comment] 2024-10-01 18:25
Im having the same issue. I'm on brave too.

**Comment by drunkwinter** [comment] 2024-10-01 20:52
Hi, I have a feeling this is a duplicate of issue #236.

This is a browser bug/regression that we've reported to Brave many months ago, and for some reason it's still on the backlog.

Please try this workaround: https://github.com/brave/brave-browser/issues/37341#issuecomment-2048166141



@black-ish Thanks for the feedback it's appreciated.

**Closed** 2024-10-31 20:58 UTC
Labels: bug
