### ISSUE TITLE
v2.3.2 not working (Tampermonkey, Firefox 95.0.2)

### ISSUE THREAD

**Issue by B1NARY9** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#111] opened 2022-01-09 15:18 UTC
I just tried to install this script on my new PC, but when i try to access a restricted video, it just shows this screen: https://imgur.com/a/J9M6dTc (text in the middle says "verify age") and the video does not play.
I downgraded to v2.3.1 and it works perfectly.

**Comment by zerodytrash** [comment] 2022-01-09 17:43
hi, thanks for reporting this issue! Do you have other browser extensions installed? Try to disable all other extensions temporarily to see if this is the problem. If it works then reactivate all extensions one by one to find out which extension causes the problem. Also, check your browser console (F12) to see if there are any error messages.

**Comment by rrrudd** [comment] 2022-01-09 19:48
Hi, I can confirm - just tested 2.3.2 with Greasemonkey first, then with Tampermonkey and it's not unlocking videos - at least this one I found today: https://www.youtube.com/watch?v=vLeTr7fYkXo . I got "successfully unlocked video" message in left bottom corner, but still video was blocked with "sign in to confirm age" message.

Checked with 2.3.1 like B1NARY9 suggested and it is working.

**Comment by zerodytrash** [comment] 2022-01-09 20:00
@rrrudd can you try the same?

> hi, thanks for reporting this issue! Do you have other browser extensions installed? Try to disable all other extensions temporarily to see if this is the problem. If it works then reactivate all extensions one by one to find out which extension causes the problem. Also, check your browser console (F12) to see if there are any error messages.

**Comment by rrrudd** [comment] 2022-01-09 20:08
@zerodytrash Sure, here are logs from Firefox console:

[2.3.1-working.log](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/files/7835816/2.3.1-working.log)
[2.3.2-not-working.log](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/files/7835817/2.3.2-not-working.log)

Also tried disabling uBlock Origin - without any change with 2.3.2 version. 2.3.1 works well with uBlock Origin turned on.

**Comment by zerodytrash** [comment] 2022-01-09 20:17
thanks @rrrudd 
```
Simple-YouTube-Age-Restriction-Bypass: Trying Unlock Method #1 (Embed) Simple YouTube Age Restriction Bypass.user.js:329:13
Simple-YouTube-Age-Restriction-Bypass: Desktop initialData fired Simple YouTube Age Restriction Bypass.user.js:329:13
Simple-YouTube-Age-Restriction-Bypass: Trying sidebar unlock Simple YouTube Age Restriction Bypass.user.js:329:13
```
The logs do not show any error. Since the error also occurs without other extensions, i assume that youtube processes the data differently for some users. This means that the new method for intercepting and unlocking the initial data (introduced in 2.3.2) does not work reliably. We will try to fix this.

**Comment by rrrudd** [comment] 2022-01-09 20:26
@zerodytrash Hmm out of curiosity I tested 2.3.2 on fresh Chrome (97.0.4692.71), just with Tampermonkey - it's working. Also checked private window in Firefox (with Tampermonkey enabled in private mode) - and it's also working.

**Comment by zerodytrash** [comment] 2022-01-09 20:35
@rrrudd ok, good to hear that you can solve the problem this way. probably youtube tests different frontend versions, which are in some cases not compatible with this method. We will try to find a solution that always works.

**Comment by postalesdeamor** [comment] 2022-01-11 01:33
Not works with latest version of Chrome
![chrome](https://user-images.githubusercontent.com/96334148/148865738-3a966aac-002b-47cb-a441-194ef480657d.jpg)

**Comment by zerodytrash** [comment] 2022-01-11 19:59
We have released a new version that hopefully fixes the problem. Can you test it again @B1NARY9 @rrrudd @postalesdeamor ?

**Comment by Maryse47** [comment] 2022-01-11 21:42
2.3.3 still doesn't work on FF96

**Comment by zerodytrash** [comment] 2022-01-11 23:10
@Maryse47 this seems to be a different bug. FireMonkey behaves similarly to Greasemonkey and needs a little workaround.

Replace in line 31
```javascript
if (typeof GM_info === "object" && GM_info.scriptHandler === "Greasemonkey" && inject) {
```
with
```javascript
if (typeof GM_info === "object" && GM_info.scriptHandler === "FireMonkey" && inject) {
```
and then it appears to work. This will be fixed in the next version.

**Comment by postalesdeamor** [comment] 2022-01-12 02:46
@zerodytrash works fine for me (Chrome) now 👍 

Thanks a lot :)

**Comment by Maryse47** [comment] 2022-01-12 16:05
@zerodytrash that made it work, thx.

BTW: the FireMonkey editor shows several code-correctness warnings (missing expected values, etc.), are those false positives?

**Comment by zerodytrash** [comment] 2022-01-12 18:11
> BTW: the FireMonkey editor shows several code-correctness warnings (missing expected values, etc.), are those false positives?

@Maryse47 there is nothing wrong with that. FireMonkey probably uses an old ECMAScript version that doesn't know some features.

**Closed** 2022-01-12 18:11 UTC
Labels: bug
