### ISSUE TITLE
Script not working in cromite

### ISSUE THREAD

**Issue by GitAlasGo** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#261] opened 2024-10-15 21:18 UTC
### What happened?

Any videos with age restriction doesn't get bypassed.

I see the repo mentions that they support cromite https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass#android

### Platform

Userscript

### Version

2.5.11

### What browser are you on?

Other (mention below with version)

### Browser version

Cromite 129.0.6668.101

### Link to the video

https://m.youtube.com/watch?v=mCYqk3-lUTY

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by joaquinito2070** [comment] 2024-10-18 09:26
I'll fix it this afternoon, but I don't know if I'll be able to get it.

**Comment by joaquinito2070** [comment] 2024-10-18 09:42
That's right, it seems that our basic plan cloud instance has expired, so it will take days to get it back, as we have to find a cloud provider, register, and also implement the proxy server on Kubernetes and also autoscaler, so that it doesn't go down anymore. More news if something happens.

**Comment by drunkwinter** [comment] 2024-10-31 21:14
Duplicate of #262, #263.

**Closed by drunkwinter** 2024-10-31 21:14 UTC
Labels: bug
