### ISSUE TITLE
Unable to unlock this video - PlayabilityError - Proxy

### ISSUE THREAD

**Issue by hm-hm-hm-hm** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#255] opened 2024-09-23 18:52 UTC
### What happened?

youtube still showed the window to verify age and woukldn't let me watch the video. i also tried installing firefox but it didn't work there either

### Platform

Userscript

### Version

2.5.11

### What browser are you on?

Opera

### Browser version

113.0.5230.86

### Link to the video

https://www.youtube.com/watch?v=FYuI4SFw4g0

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/7b720d6f-63c8-44df-8d26-163c73040628)

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by hm-hm-hm-hm** [comment] 2024-09-23 18:57
when i tried on firefox with violentmonkey instead of tapermonkey it said "Unable to unlock this video 🙁 - More information in the developer console (PlayabilityError)" but idk how to use that console

**Comment by drunkwinter** [comment] 2024-09-24 01:57
Hi, thanks for reporting.

I have identified the problem, unfortunately I don't think this will be a quick and easy fix. But we will try to have it resolved as soon as possible.

**Comment by Bolongna** [comment] 2024-09-24 03:03
Still getting the same error as before but I'm not in any rush.

**Comment by redmanmale** [comment] 2024-09-25 18:12
> if you refresh the page bypass will works

no luck

**Comment by drunkwinter** [comment] 2024-09-30 17:12
So an update about this. I've been looking at this for the past week now and the only solution I've been able to find is to play those videos at 360p, because of some new YouTube security measures. When I've got some more free time on my hands I'll try and see if I can find a real solution.

**Comment by Adamo1618** [comment] 2024-10-26 07:32
Videos linked in Reddit posts play just fine. Example: https://www.reddit.com/r/Helldivers/comments/1flboim/the_official_super_earth_national_anthem/
When visiting the Youtube video page itself I'm forced to log in. Can you use Reddit's method to bypass it?

**Comment by Adamo1618** [comment] 2024-10-26 07:37
Workaround for the time being: replace the "watch?v=" with "embed/", including the slash. This video works fine: https://www.youtube.com/embed/WcGJmev2718

**Comment by Gujal00** [comment] 2024-11-01 10:14
`embed` trick does not work for `https://www.youtube.com/watch?v=xkRvqbzKGi4`

**Comment by highschooldropout** [comment] 2024-11-02 08:34
Any update on this? Was working for me till last week but I had to reinstall a bunch of extensions and here I am.

**Unable to unlock this video 🙁 - More information in the developer console (ProxyError)**

**Comment by drunkwinter** [comment] 2024-11-09 06:17
Closing this in favor of other already opened issues.

Duplicate of https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/263.

**Closed by drunkwinter** 2024-11-09 06:17 UTC
Labels: bug
