### ISSUE TITLE
no wokrie

### ISSUE THREAD

**Issue by Schlabbadabadoo** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#237] opened 2024-04-29 07:17 UTC
# Description
it just is freezing my youtube and these r the errors its giving

# Log
```
09:16:14 [INFO] Script injected (https://www.youtube.com/watch?v=vf0B0yj7Kas)
09:16:14 [ERROR] Failed to intercept Request(); Cannot read properties of null (reading 'host')
    at isGoogleVideoUrl (<anonymous>:80:20)

09:16:14 [ERROR] Failed to intercept Request(); Cannot read properties of null (reading 'host')
    at isGoogleVideoUrl (<anonymous>:80:20)

09:16:14 [ERROR] Failed to intercept Request(); Cannot read properties of null (reading 'host')
    at isGoogleVideoUrl (<anonymous>:80:20)

09:16:14 [ERROR] Failed to intercept Request(); Cannot read properties of null (reading 'host')
    at isGoogleVideoUrl (<anonymous>:80:20)

09:16:14 [ERROR] Failed to intercept Request(); Cannot read properties of null (reading 'host')
    at isGoogleVideoUrl (<anonymous>:80:20)

09:16:15 [INFO] playerResponse property set, contains sidebar: true
09:16:15 [INFO] Trying Player Unlock Method #2 (TV Embedded Player)

```

**Comment by drunkwinter** [comment] 2024-04-29 13:00
Are you using Brave by any chance?

**Comment by Schlabbadabadoo** [comment] 2024-04-29 23:18
Yes

**Comment by drunkwinter** [comment] 2024-04-29 23:21
Closing this as a duplicate of #236.

**Closed** 2024-04-29 23:22 UTC
