### ISSUE TITLE
Age verification is blocking videos

### ISSUE THREAD

**Issue by uaciej** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#154] opened 2022-08-31 07:30 UTC
### What happened?

Since 2 days the age verification is blocking videos again.

### Platform

Extension

### Version

4.16.1

### What browser are you on?

Chrome

### Browser version

105.0.5195.54

### Link to the video

https://www.youtube.com/watch?v=365IFG78gSM&ab_channel=Atrioc

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/84397706/187619163-54e50476-1643-4c4f-9639-74430d9a7e02.png)

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment] 2022-08-31 19:00
Hi, thanks for reporting. I cannot seem to reproduce the issue you're having. 

Couple questions:

- Can you check the version of the extension again? The one you provided doesn't exist, the latest is 2.5.2.

- Are you sure it's the extension and not the userscript, because we don't have a Chrome release yet.

- Do you see any notifications/toasts indicating the video was unlocked or not?

- Could you provide logs from either the Developer Console (F12) and/or the Debug Log from the extension window?

**Comment by zerodytrash** [comment] 2022-08-31 19:15
I can't reproduce it either.

**Comment by zerodytrash** [comment] 2022-09-18 21:10
Since the user gave wrong version information, I assume a layer 8 problem. Will close this. If the user wants to provide more information, we can open it again.

**Closed by zerodytrash** 2022-09-18 21:10 UTC
Labels: bug, waiting for response, cannot reproduce
