### ISSUE TITLE
Exttension breaks Youtube Page for Xbox Channel Videos

### ISSUE THREAD

**Issue by ericplane** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#251] opened 2024-08-22 09:50 UTC
### What happened?

When I load onto the Xbox channel it crashes and also if I click on one of their gamescom livestreams it crashes the youtube site. They are age restricted videos (Require you to hit a button saying "I understand and wish to proceed" but I'm guessing this causes the extension to crash when the user is not logged into the youtube site. I'm not logged into YouTube and therefore that might be the issue but I'm unsure.

### Platform

Userscript

### Version

2.5.10

### What browser are you on?

Brave

### Browser version

1.68.141

### Link to the video

https://www.youtube.com/watch?v=67DimNfopZE

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/694c0afc-65ef-4944-a498-7d3ce2245243)

### About you

- [X] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment] 2024-08-22 09:53
Duplicate of #236.

Please see the issue above.

**Closed by drunkwinter** 2024-08-22 09:53 UTC
Labels: bug
