### ISSUE TITLE
Not working in browsers without ECMAScript 2020 support

### ISSUE THREAD

**Issue by computerfan0** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#57] opened 2021-08-23 22:56 UTC
I am trying to watch age restricted videos but am still getting forced to verify my ID even though I am using both this script and a VPN set to Canada.

**Comment by zerodytrash** [comment] 2021-08-23 23:04
Please provide the link to the video and the error message from the developer console (F12)

**Comment by computerfan0** [comment] 2021-08-23 23:44
I was getting it on various videos but can't remember any of them. They came up when searching for "age restricted test".

**Comment by zerodytrash** [comment] 2021-08-23 23:54
- what browser are you using?
- do you see a red "Unable to unlock this video :(" message below the player?
- what error message do you find in the developer console?

I need more information otherwise I can't help you.

**Comment by krystian3w** [comment] 2021-08-24 21:44
Script may no works with Waterfox Classic 2021.04 - detected  by @decembre

**Comment by zerodytrash** [comment] 2021-08-24 22:23
> Script may no works with Waterfox Classic 2021.04

Yes, thats because Waterfox Classic doesn't support ECMAScript 2020 features like "optional chaining" used by this script :(

**Comment by decembre** [comment] 2021-08-24 22:24
Thanks:
My report about this problem to Waterfox:
<a href="https://github.com/WaterfoxCo/Waterfox/issues/2221">[WaterFox Classic] Unsupported JS functions/API ? - (Make an userscript Unusable with Waterfox Classic) #2221</a>

**Comment by xlovinglyx** [comment] 2021-08-28 04:10
HI zerody, not working here either. 

I confirm you the same issue with Palemoon as with Waterfox. a workaround would be nice.

**Comment by xlovinglyx** [comment] 2021-08-28 04:14
ex: https://www.youtube.com/watch?v=9OTkhsJUK0U

**Comment by DrunkWinter** [comment] 2021-08-28 11:13
At some point we could make a build step and compile the release to be compatible with older browsers. Might give it a try if this is needed.

**Comment by xlovinglyx** [comment] 2021-08-28 14:37
that would be wonderful ))

**Comment by krystian3w** [comment] 2021-08-28 18:54
> `9OTkhsJUK0U`

works on Firefox 91.0.3, so no geolocked and not hidden by paid membership if broken with your Firefox 91 / Chrome 92 (and other updated chromium browser) / Safari 14 so needed is error log from dev tools console.

For PaleMoon/Basilisk/Waterfox Classic maybe better create mega theard as new issue.

**Comment by DrunkWinter** [comment] 2021-08-31 17:18
I'm currently working on it as seen above. Are any of you willing to test this out and report back if this fixes the issue?

[Simple-YouTube-Age-Restriction-Bypass.user.zip](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/files/7085678/Simple-YouTube-Age-Restriction-Bypass.user.zip)

**Comment by decembre** [comment] 2021-08-31 20:13
> 
> 
> I'm currently working on it as seen above. Are any of you willing to test this out and report back if this fixes the issue?
> 

Tested (tampermonkey + Waterfox Classic 56.5) but not working:
Go to the Login page....
;-(

Note it's maybe due to the formating?
After copy/paste in tampermonkey editor , i see a red cross error before your code....

**Comment by krystian3w** [comment] 2021-08-31 20:20
But still works in Firefox 92 + Tampermonkey.

**Comment by xlovinglyx** [comment] 2021-08-31 20:27
not working on palemoon.

**Comment by DrunkWinter** [comment] 2021-08-31 21:16
Unfortunately I have bad news for you guys.

It's until I downloaded one of the browsers to realize how old they were. Waterfox classic was not available anymore from the official website (which also proves my point).

The browsers you guys are using don't have 'Web Components' support, which means you get a really old version of YouTube without 'Polymer' because it uses that technology!

So now the problem isn't really that we have to support an old version of JavaScript, but rather an old version of YouTube, which in turn means entirely different logic/code.

Even if we tried to support the old browser feature set by compiling it, it would still not work! That is because this script was designed to work with the "new" YouTube webpage and trying to support the old YouTube with the current one, would probably mean a whole rewrite!

**Comment by DrunkWinter** [comment] 2021-08-31 22:19
Had to retract the previous comment, because I was completely wrong.

I will investigate Palemoon, but Waterfox Classic is not available anymore though the official site.

@xlovinglyx What Userscript manager do you use and could you provide me a link to it?

**Comment by DrunkWinter** [comment] 2021-08-31 23:12
Ok after hard looking I think I'm confident that I've found the problem and a possible solution. This is probably gonna be a 2 stage fix.

**Comment by zerodytrash** [comment] 2021-08-31 23:28
In Waterfox Classic the execution works with the following babel.config.js preset:
```
targets: {
    firefox: "47",
  },
```

**Comment by DrunkWinter** [comment] 2021-08-31 23:37
> In Waterfox Classic the execution works with the following babel.config.js preset:
> 
> ```
> targets: {
>     firefox: "47",
>   },
> ```

@zerodytrash Second problem lies here. `window.eval` or `initUnlocker.toString()` somehow corrupts the code and we get `ReferenceError: _typeof is not defined` on Palemoon. Without the if check (executing the function directly) it works as expected.
Do we still need the eval call?
```javascript
if ((typeof GM_info === "undefined" ? "undefined" : _typeof(GM_info)) === "object" && GM_info.scriptHandler === "Greasemonkey") {
    window.eval("(" + initUnlocker.toString() + ")();");
} else {
    initUnlocker();
}
```

**Comment by zerodytrash** [comment] 2021-08-31 23:41
> Do we still need the eval call?

A direct execution (without `eval`) would not work with Greasemonkey. Tampermonkey and other script managers have no problems with it.

**Comment by DrunkWinter** [comment] 2021-08-31 23:44
> > Do we still need the eval call?
> 
> A direct execution (without `eval`) would not work with Greasemonkey. Tampermonkey and other script managers have no problems with it.

That's the weird thing, because I used Greasemonkey because it looks like it's the only option for Palemoon.

**Comment by zerodytrash** [comment] 2021-09-01 00:01
>  window.eval or initUnlocker.toString() somehow corrupts the code and we get ReferenceError: _typeof is not defined on Palemoon. Without the if check (executing the function directly) it works as expected.

I assume the following (not tested):
`window.eval` is executed in a different context and the helper variable (?) `_typeof` is only present in the script context. Greasemonkey separates the script from the window context. This is a part of the security model. So `_typeof` would have to be transferred to the window first. Babel is probably not designed for this.

**Comment by DrunkWinter** [comment] 2021-09-01 00:07
> > window.eval or initUnlocker.toString() somehow corrupts the code and we get ReferenceError: _typeof is not defined on Palemoon. Without the if check (executing the function directly) it works as expected.
> 
> I assume the following (not tested):
> `window.eval` is executed in a different context and the helper variable (?) `_typeof` is only present in the script context. Greasemonkey separates the script from the window context. This is a part of the security model. So `_typeof` would have to be transferred to the window first. Babel is probably not designed for this.

We could maybe use a different injection method to get around this. What do you think?

```javascript
const nScript = document.createElement('script', { innerHTML: "(" + initUnlocker.toString() + ")();" });
document.head.append(nScript);
```

**Comment by zerodytrash** [comment] 2021-09-01 00:11
> We could maybe use a different injection method to get around this. What do you think?

The web page (YouTube) does not know `_typeof`, because declarations from the script context are not available through the window.

**Comment by zerodytrash** [comment] 2021-09-01 00:12
Is there perhaps a way to tell babel to declared such variables per function instead globally?

**Comment by DrunkWinter** [comment] 2021-09-01 01:40
> Is there perhaps a way to tell babel to declare such variables per function instead globally?

Was just about to give up and then I got a clever idea ;)

```javascript
if (GM_info.scriptHandler === "Greasemonkey" && !arguments[0]) {
    window.eval("(" + arguments.callee.toString() + ")(true);");
    return;
}
```

We then can remove the `initUnlocker` function since we are already in an IIFE and we pass the `strict: false` option to Rollup, because `arguments.callee` does not work in strict mode.

This would be more than fine, until we find a way to do it within the bundle process.

**Comment by xlovinglyx** [comment] 2021-09-01 03:14
if i get it right drunkwinter, u found an idea but havent got time to completly write it for the final js ?

**Comment by DrunkWinter** [comment] 2021-09-01 03:27
> if i get it right drunkwinter, u found an idea but havent got time to completly write it for the final js ?

Not at all, consider it almost done ;)
This one should hopefully work.

[Simple-YouTube-Age-Restriction-Bypass.user.zip](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/files/7088009/Simple-YouTube-Age-Restriction-Bypass.user.zip)

**Comment by decembre** [comment] 2021-09-01 07:43
Tested:
Tested (tampermonkey + Waterfox Classic 56.5)
WORK fine!
;-)

**Comment by DrunkWinter** [comment] 2021-09-01 12:13
> Tested for:
> [https://www.youtube.com/watch?v=9OTkhsJUK0U](url)
> with:
> Tampermonkey + Waterfox Classic 56.5
> WORK fine!
> ;-)

Happy to hear!

Can you do one last test for me please and see if this one works too?

[Simple-YouTube-Age-Restriction-Bypass.user.zip](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/files/7090917/Simple-YouTube-Age-Restriction-Bypass.user.zip)

**Comment by decembre** [comment] 2021-09-01 12:28
Re -Tested with your very last version:
Tampermonkey + Waterfox Classic 56.5
On video:
https://www.youtube.com/watch?v=9OTkhsJUK0U
All is working too.
Fast and perfect.
Thanks....

**Comment by xlovinglyx** [comment] 2021-09-02 10:42
You're the king drunk winter! i was finding it sooo creepy that youtube asks the scanning of an id to then resell private information. works like a charm ))

**Comment by xlovinglyx** [comment] 2021-09-05 11:12
Hi drunkwinter, this has nothing to do with the topic but since u seem to know how to play with greasemonkey for palemoon,
i was wondering if you could fix this: https://chrome-extension-downloader.com/0deebe7f3cbee2ca25c97cbaa54c78f0/https://chrome.google.com/webstore/detail/auto-replay-for-youtube/mcdpnidfhfjfbafmpppcplcejgepadbo?hl=en-US&gl=CA.crx

it stopped working on youtube, i still have the script of version code 3.3 & the script part of 3.4 above re-added to greasemonkey didn't work..

**Comment by DrunkWinter** [comment] 2021-09-05 14:55
> Hi drunkwinter, this has nothing to do with the topic but since u seem to know how to play with greasemonkey for palemoon,
> i was wondering if you could fix this: https://chrome-extension-downloader.com/0deebe7f3cbee2ca25c97cbaa54c78f0/https://chrome.google.com/webstore/detail/auto-replay-for-youtube/mcdpnidfhfjfbafmpppcplcejgepadbo?hl=en-US&gl=CA.crx
> 
> it stopped working on youtube, i still have the script of version code 3.3 & the script part of 3.4 above re-added to greasemonkey didn't work..

First of all, the extension you are referring to is not open-source and second It's really not worth fixing it, since it's already a YouTube feature. Just right mouse click on a video and then click on 'loop'. 

![image](https://user-images.githubusercontent.com/38593134/132131323-dcf8d572-028d-404e-ba3d-d415fee7018f.png)

**Comment by krystian3w** [comment] 2021-09-05 15:11
But addon can loop few seconds instead all video.

Something like pages:

https://looptube.io/

https://youtubeloop.net/

**Comment by DrunkWinter** [comment] 2021-09-05 16:40
@krystian3w @xlovinglyx 

These extensions do the same thing.

https://chrome.google.com/webstore/detail/looper-for-youtube/iggpfpnahkgpnindfkdncknoldgnccdg
&
https://chrome.google.com/webstore/detail/magic-actions-for-youtube/abjcfabbhafbcdfjoecdgepllmpfceif

**Comment by krystian3w** [comment] 2021-09-05 16:49
But exist good quality converter crx to UPX.xpi or user.js?

**Comment by DrunkWinter** [comment] 2021-09-05 16:51
> But exist good quality converter crx to UPX.xpi or user.js?

Maybe what @krystian3w uses? https://chrome-extension-downloader.com/

**Comment by krystian3w** [comment] 2021-09-05 16:54
But palemoon prefere UPX plafrom and zip/xpi file.

https://repo.palemoon.org/MoonchildProductions/UXP `Unified XUL Platform`/`XPCOM`.

**Comment by DrunkWinter** [comment] 2021-09-05 17:01
> But palemoon prefere UPX plafrom and zip/xpi file.
> 
> https://repo.palemoon.org/MoonchildProductions/UXP `Unified XUL Platform`/`XPCOM`.

Yeah sorry don't know of any.. Maybe you can search in Firefox addons. https://addons.mozilla.org/en-US/firefox/extensions/

**Comment by krystian3w** [comment] 2021-09-05 18:38
That is WebExtension, MoonChild removed support WebExtension in Basilik/PaleMoon.

**Comment by xlovinglyx** [comment] 2021-09-05 19:04
"Maybe what @xlovinglyx uses? https://chrome-extension-downloader.com/"

No drunkwinter, (I'm a pale moon user, your previous fix for waterfox worked in palemoon too)

I was asking a script based fix, & all other comments, made a point, the addon loops specific parts
People would like to loop only like in long concerts. if you open the link i initially gave you, the crx
file, you'll have the script inside, adapting it to greasemonkey for palemoon would be as good for
palemoon as for waterfox. so it's "not useless", but it can only become a "loss" if you don't want to
fix that script for a reason or another.

**Comment by Purfview** [comment] 2021-09-11 00:10
> 
> 
> > if i get it right drunkwinter, u found an idea but havent got time to completly write it for the final js ?
> 
> Not at all, consider it almost done ;)
> This one should hopefully work.
> 
> [Simple-YouTube-Age-Restriction-Bypass.user.zip](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/files/7088009/Simple-YouTube-Age-Restriction-Bypass.user.zip)


> 
> [Simple-YouTube-Age-Restriction-Bypass.user.zip](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/files/7090917/Simple-YouTube-Age-Restriction-Bypass.user.zip)

Both don't work with Violentmonkey + Waterfox Classic 2021.08.1

**Comment by DrunkWinter** [comment] 2021-09-11 00:53
> Violentmonkey

Tested it on Waterfox Classic 2021.08.1 with Violentmonkey and everything seems to work accordingly. 
Make sure you disable the old version if you didn't already overwrite it, also make sure to disable all other extensions you might have and see if that works. If you still have the issue, then it's best to wait till the patch is officially released and if you then get the same result, it might be better if you created a separate issue/report.

When the patch releases (soon) this issue will be closed.

**Comment by Purfview** [comment] 2021-09-11 03:08
> 
> Tested it on Waterfox Classic 2021.08.1 with Violentmonkey and everything seems to work accordingly.
> 
> Make sure you disable the old version if you didn't already overwrite it, also make sure to disable all other extensions you might have and see if that works.

Created the new Waterfox Classic profile.
Restarted Waterfox Classic into the new profile.
Installed Violentmonkey 2.13
Installed [Simple-YouTube-Age-Restriction-Bypass.user.zip](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/files/7090917/Simple-YouTube-Age-Restriction-Bypass.user.zip)
Tried: https://www.youtube.com/watch?v=9OTkhsJUK0U

Still I see "Verify your age" message... it's 2021.08.1 (64-bit) on Win7.

**Comment by krystian3w** [comment] 2021-09-11 10:02
You installed without rename/unpack?

**Comment by Purfview** [comment] 2021-09-11 14:43
> 
> 
> You installed without rename/unpack?

Huh, of course I extracted JS file from ZIP archive. :)

**Comment by krystian3w** [comment] 2021-09-11 19:05
So demo links end error from devtools are needed.

We don't have :crystal_ball:.

**Comment by DrunkWinter** [comment] 2021-09-11 19:14
Like I said, wait for the official patch before opening a new issue. Your issue has likely nothing to do with this one.

**Comment by zerodytrash** [comment] 2021-09-17 15:42
The latest version should be compatible with Waterfox Classic.

**Closed by zerodytrash** 2021-09-17 15:42 UTC

**Comment by Purfview** [comment] 2021-09-17 16:55
@ DrunkWinter 

Latest v2.2.1 works like a charm.
Thanks guys.
