### ISSUE TITLE
No Description text

### ISSUE THREAD

**Issue by ThingOfAnimeForever2006** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#159] opened 2022-10-20 15:44 UTC
### What happened?

can i show the description text please? i can't show it. awww.

### Platform

Extension

### Version

2.4.6

### What browser are you on?

Chrome

### Browser version

100.0.4896.127

### About you

- [X] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment] 2022-10-20 16:18
Hi, I assume you build the extension yourself and loaded it into Chrome? Have you tried the latest version `2.5.2`? There have been allot of changes since then.

I am unable to reproduce the issue that you're having, maybe providing the video URL will help.

**Comment by interrupt-routine** [comment] 2022-10-21 22:22
I have the same problem on Firefox 106.0.1, using the extension, version 2.5.2. When inspecting the HTML, i can find the description in 

```html
<body dir="ltr" no-y-overflow>
  <script nonce="...">
    var ytInitialPlayerResponse = {
       ..., "shortDescription" : "description is there"
}
```

[video example](https://www.youtube.com/watch?v=vgCVHdFnj54)

debug log:
````
00:13:24 [INFO] Script injected (https://www.youtube.com/watch?v=vgCVHdFnj54)
00:13:24 [INFO] playerResponse property set, contains sidebar: false
00:13:24 [INFO] Trying Player Unlock Method #2 (TV Embedded Player)
00:13:25 [INFO] Trying Next Unlock Method #2 (Account Proxy)
00:13:27 [INFO] playerResponse property set, contains sidebar: true
00:13:27 [INFO] playerResponse property set, contains sidebar: false
```

**Comment by drunkwinter** [comment] 2022-10-22 15:07
Thanks guys, found the problem. The proxy bypass for descriptions seems broken.

**Comment by drunkwinter** [comment] 2022-10-22 15:53
Fixed in the main branch, just needs a release.

@zerodytrash

**Comment by zerodytrash** [comment] 2022-10-22 17:33
Release created. Thanks @drunkwinter for the quick fix.

**Closed by zerodytrash** 2022-10-22 17:33 UTC
Labels: bug
