### ISSUE TITLE
Plugin not working all of a sudden (youtube patch ?)

### ISSUE THREAD

**Issue by charlie59876** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#198] opened 2023-07-28 16:48 UTC
### What happened?

This is on the user script version, not sure if the plugin still works, but the script is still giving me "verify your age" all of a sudeen on the latest update. this plugin worked fine before

### Platform

Userscript

### Version

2.5.7

### What browser are you on?

Firefox

### Browser version

115.0.3 (64-bit)

### Link to the video

https://www.youtube.com/watch?v=GhK5S7cO8aw

### Screenshots or Videos

![image](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/assets/38352981/70f8da71-caa4-4fcd-b856-a2ae60060fd3)

### About you

- [X] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment] 2023-07-28 22:41
Could not reproduce the issue on my end. Make sure the userscript is enabled and running. Also make sure to disable other scripts/plugins which might cause a conflict.

**Comment by i300220** [comment] 2023-08-03 17:59
Stopped working as well on Brave [Version 1.46.133 Chromium: 108.0.5359.71 (Official Build) (64-bit)]

Still working fine on Slimjet Version 37.0.2.0 (based on Chromium 107.0.5304.62) (Official Build) (32-bit)

Version
2.5.7
Updated 2 weeks ago after it seemed broken on Brave.  Worked fine for a while though until I tried it again today.

Using https://www.tampermonkey.net/changelog.php?version=4.19.0

No big deal, just reporting.

Best!

**Comment by drunkwinter** [comment] 2023-08-03 22:59
@i300220 Could you describe what happens, does it give you an error message or do you only see the "verify your age" screen?

Also could you screenshot the logs in the developer console? (Press F12 and filter for "Simple-YouTube-Age-Restriction-Bypass".)

**Comment by i300220** [comment] 2023-08-04 15:01
Argh!  It's intermittent. It was broken yesterday for some time, I got the exact same screen as in the first message.  No other YT error message.  I opened the developer console to confirm the fault was in the script and it was complaining about something not working or not implemented.  Can't remember the exact error though as I was busy at that point.

Can't reproduce anymore.  I'll post all pertinent debug info when/if it happens again.  Sorry for the inconvenience.

**Comment by girlmaya** [comment] 2023-08-05 13:29
I'm getting `An error occurred. Please try again later. (Playback ID: XP4HKqZPtZSG9lhL)` , userscript 2.5.7, here's a video link: https://www.youtube.com/watch?v=LvEDqZ75P4c

**Comment by drunkwinter** [comment] 2023-08-05 22:00
@girlmaya Thanks, was able to reproduce. Will investigate.

**Comment by drunkwinter** [comment] 2023-08-05 23:59
@girlmaya I've opened a new issue (#202), since it's a different problem than what the OP was having and for better issue tracking purposes.

**Comment by drunkwinter** [comment] 2023-08-06 23:51
@charlie59876 That likely means it's somehow not running. Maybe the script is disabled? Or some other issue?

An easy way to test this is just to try installing it on another browser or system and see if it works there.

**Comment by drunkwinter** [comment] 2023-08-07 22:02
> I just tested it on chrome and i got the error something went wrong which is i believe the same that girlmaya is getting and this in the console 
![image](https://user-images.githubusercontent.com/38352981/258932457-8df66bcb-5601-4b5a-bb0e-8cbb52a2bd0b.png) 
But also the audio still plays which is odd, but the video and video controls don't load. this doesn't happen on firefox on firefox nothing shows up other than the normal youtube verify age and the plugin doesn't seem to show anything in the console

This issue was reported in #205 recently and fixed. The fix will be included in the next release. 

As for the other issue of nothing showing up on Firefox is very unusual. Anyway the next release should be out tomorrow or the day after.

I'll keep this issue open in case the next release doesn't fix it.

**Comment by drunkwinter** [comment] 2023-08-09 14:13
@charlie59876  Could you please test this on [v2.5.9](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/releases/tag/v2.5.9) again?

**Comment by drunkwinter** [comment] 2023-08-24 11:42
I'm assuming this is fixed.

**Closed by drunkwinter** 2023-08-24 11:42 UTC
Labels: bug, waiting for response, cannot reproduce

**Comment by Vmthyagaraj** [comment] 2023-08-24 11:52
Feedback

**Comment by drunkwinter** [comment] 2023-08-30 18:48
@charlie59876 

The script is most likely not running like I previously said. Make sure the script is enabled and running on the website. Maybe try toggling it off and then on again if it's already enabled. This looks like an install/configuration issue to me.

![image](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/assets/38593134/3db57e43-210c-4e74-8114-25d158a09b2e) ![image](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/assets/38593134/af07f58b-4748-4979-82c3-87f162d45efb)
