### ISSUE TITLE
Script doesn't work anymore (or work randomly) since 02.10.2024

### ISSUE THREAD

**Issue by nicitaacom** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#258] opened 2024-10-02 18:21 UTC
### What happened?

It's NOT dublicate of #236 

I see "verify your age"

https://www.youtube.com/watch?v=zXwzLcw6480&

But sometimes it work
![image](https://github.com/user-attachments/assets/ed33e727-18fe-4d4e-b229-f4f790e94a6e)

https://www.youtube.com/watch?v=zXwzLcw6480&ab_channel=YchiYroki

![image](https://github.com/user-attachments/assets/316d0be2-8961-4783-a026-b2a3f41e67f6)

### Platform

Extension

### Version

2.5.10

### What browser are you on?

Chrome

### Browser version

126.0.6478.126

### Screenshots or Videos

Tampermonkey
5.2.0

Simple YouTube Age Restriction Bypass
2.5.10

## Update

For shorts it doesn't work as well
![image](https://github.com/user-attachments/assets/ad0e41e6-8e9e-4504-9864-95d3bc31f9e2)

### About you

- [X] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment] 2024-10-31 21:17
Closing this in favor of other already opened issues.

Duplicate of https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/262, https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/263.

**Closed by drunkwinter** 2024-10-31 21:17 UTC
Labels: bug
