### ISSUE TITLE
Userscript not working

### ISSUE THREAD

**Issue by Leegmus** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#268] opened 2024-11-08 04:10 UTC
### What happened?

I used this userscript, but somehow; it doesn't work. Wtf?

### Platform

Userscript

### Version

2.5.11

### What browser are you on?

Opera

### Browser version

128.0.6613.178

### Link to the video

https://www.youtube.com/watch?v=eBi_vKsOfUU

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/31a63303-b235-42b5-aa72-b618c76154ec)

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment] 2024-11-09 06:18
Duplicate of https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/263.

**Closed by drunkwinter** 2024-11-09 06:18 UTC
Labels: bug
